# Auto-generated using compose2nix v0.3.1.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
    defaultNetwork.settings = {
      # Required for container networking to be able to use names.
      dns_enabled = true;
    };
  };

  # Enable container name DNS for non-default Podman networks.
  # https://github.com/NixOS/nixpkgs/issues/226365
  networking.firewall.interfaces."podman+".allowedUDPPorts = [ 53 ];

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."mazanoke" = {
    image = "ghcr.io/civilblur/mazanoke:latest";
    ports = [
      "3474:80/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=mazanoke"
      "--network=mazanoke_default"
    ];
  };
  systemd.services."podman-mazanoke" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "podman-network-mazanoke_default.service"
    ];
    requires = [
      "podman-network-mazanoke_default.service"
    ];
    partOf = [
      "podman-compose-mazanoke-root.target"
    ];
    wantedBy = [
      "podman-compose-mazanoke-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-mazanoke_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f mazanoke_default";
    };
    script = ''
      podman network inspect mazanoke_default || podman network create mazanoke_default
    '';
    partOf = [ "podman-compose-mazanoke-root.target" ];
    wantedBy = [ "podman-compose-mazanoke-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-mazanoke-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
