# Auto-generated using compose2nix v0.3.1.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
    defaultNetwork.settings = {
      # Required for container networking to be able to use names.
      dns_enabled = true;
    };
  };

  # Enable container name DNS for non-default Podman networks.
  # https://github.com/NixOS/nixpkgs/issues/226365
  networking.firewall.interfaces."podman+".allowedUDPPorts = [ 53 ];

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."metadata-remote" = {
    image = "ghcr.io/wow-signal-dev/metadata-remote:latest";
    environment = {
      "PGID" = "1000";
      "PUID" = "1000";
    };
    volumes = [
      "/mnt/nfs/music/:/music:rw"
    ];
    ports = [
      "8338:8338/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=metadata-remote"
      "--network=metadata-remote_default"
    ];
  };
  systemd.services."podman-metadata-remote" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-metadata-remote_default.service"
    ];
    requires = [
      "podman-network-metadata-remote_default.service"
    ];
    partOf = [
      "podman-compose-metadata-remote-root.target"
    ];
    wantedBy = [
      "podman-compose-metadata-remote-root.target"
    ];
    unitConfig.RequiresMountsFor = [
      "/mnt/nfs/music/"
    ];
  };

  # Networks
  systemd.services."podman-network-metadata-remote_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f metadata-remote_default";
    };
    script = ''
      podman network inspect metadata-remote_default || podman network create metadata-remote_default
    '';
    partOf = [ "podman-compose-metadata-remote-root.target" ];
    wantedBy = [ "podman-compose-metadata-remote-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-metadata-remote-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
